# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eazzy_demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      # logging.level.org.springframework.data.redis.connection: DEBUG
      # logging.level.io.lettuce.core: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
      # show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
